### ISSUE TITLE
Integration did not work on 2025.1.2

### ISSUE THREAD

**Issue by Floppik** [Makave1i/terneo_thermostat#22]
Platform error 'climate' from integration 'terneo' - cannot import name 'CURRENT_HVAC_HEAT' from 'homeassistant.components.climate.const' (/usr/src/homeassistant/homeassistant/components/climate/const.py)
Platform error 'climate' from integration 'terneo' - cannot import name 'CURRENT_HVAC_HEAT' from 'homeassistant.components.climate.const' (/usr/src/homeassistant/homeassistant/components/climate/const.py)

**Comment by Makave1i** [comment]
it seems like it's in an older version, in the current version of 'climate.py' I don't see anything related to 'CURRENT_HVAC_HEAT'. 
maybe try updating the component

**Comment by Floppik** [comment]
My bad. Update one more time and problem has gone.
